[build]
target = "avr-specs/avr-atmega328p.json"

[target.'cfg(target_arch = "avr")']
#runner = "ravedude nano -cb 57600"
runner = "ravedude nano-new -cb 57600 -P /dev/tty.usbserial-110"

[unstable]
build-std = ["core"]
