[build]
target = ".cargo/targets/avr-atmega328p.json"

[target.'cfg(target_arch = "avr")']
runner = "ravedude nano-new -cb 57600 -P /dev/ttyUSB0"
#runner = "ravedude nano-new -cb 57600 -P /dev/tty.usbserial-110"

[unstable]
build-std = ["core"]
